# Name for your workflow
name: Node.js and Groovy CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push events for the "main" branch
  push:
    branches: [ "main" ]
  # Triggers the workflow on pull request events for any branch
  pull_request:
    branches: [ "*" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-and-validate"
  build-and-validate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 1. Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Sets up the Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # Use a Long-Term Support (LTS) version of Node.js
          cache: 'npm' # Caches npm dependencies for faster builds

      # 3. Sets up the Java environment required to run Groovy
      - name: Setup Java (for Groovy)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # A popular, open-source JDK distribution
          java-version: '17' # Groovy runs on the JVM

      # 4. Installs your Node.js project dependencies
      - name: Install Node.js Dependencies
        run: npm ci # 'ci' is faster and safer for automated environments than 'install'

      # 5. Run your Node.js tests (if you have any)
      - name: Run Node.js Tests
        run: npm test # Assumes your test command is 'npm test'

      # 6. Run your Groovy schema validation script
      - name: Run Groovy Schema Validation
        run: groovy your-schema-validator.groovy # <-- IMPORTANT: Change this filename!